Modernize Testo runtime and tooling

diff --git a/src/testo_guest_additions/pkg/linux/postinst b/src/testo_guest_additions/pkg/linux/postinst
--- a/src/testo_guest_additions/pkg/linux/postinst
+++ b/src/testo_guest_additions/pkg/linux/postinst
@@ -1,11 +1,21 @@
 #!/bin/bash -e
 
-if [ -x "$(command -v update-rc.d)" ]; then
-	update-rc.d testo-guest-additions defaults
+if [ -x "$(command -v systemctl)" ]; then
+	if ! systemctl daemon-reload; then
+		echo "W: 'systemctl daemon-reload' failed"
+	fi
+	if ! systemctl enable testo-guest-additions; then
+		echo "W: 'systemctl enable testo-guest-additions' failed"
+	fi
+	if ! systemctl start testo-guest-additions; then
+		echo "W: 'systemctl start testo-guest-additions' failed"
+	fi
+else
+	if [ -x "$(command -v update-rc.d)" ]; then
+		update-rc.d testo-guest-additions defaults
+	fi
+	if [ -x "$(command -v chkconfig)" ]; then
+		chkconfig testo-guest-additions on
+	fi
+	service testo-guest-additions start
 fi
-
-if [ -x "$(command -v chkconfig)" ]; then
-	chkconfig testo-guest-additions on
-fi
-
-service testo-guest-additions start
diff --git a/src/testo_guest_additions/pkg/linux/prerm b/src/testo_guest_additions/pkg/linux/prerm
--- a/src/testo_guest_additions/pkg/linux/prerm
+++ b/src/testo_guest_additions/pkg/linux/prerm
@@ -1,11 +1,18 @@
 #!/bin/bash -e
 
-service testo-guest-additions stop
-
-if [ -x "$(command -v update-rc.d)" ]; then
-	update-rc.d testo-guest-additions remove
-fi
-
-if [ -x "$(command -v chkconfig)" ]; then
-	chkconfig testo-guest-additions off
+if [ -x "$(command -v systemctl)" ]; then
+	if ! systemctl stop testo-guest-additions; then
+		echo "W: 'systemctl stop testo-guest-additions' failed"
+	fi
+	if ! systemctl disable testo-guest-additions; then
+		echo "W: 'systemctl disable testo-guest-additions' failed"
+	fi
+else
+	service testo-guest-additions stop
+	if [ -x "$(command -v update-rc.d)" ]; then
+		update-rc.d testo-guest-additions remove
+	fi
+	if [ -x "$(command -v chkconfig)" ]; then
+		chkconfig testo-guest-additions off
+	fi
 fi
